# store config in _data for livereload

## site info
author: "PhÃºc BÃ¹i"
title: "PhÃºc's Blog"
title_sep: " | "
description: "Váº«n Ä‘ang suy nghÄ© nÃªn viáº¿t gÃ¬ á»Ÿ Ä‘Ã¢y ğŸ¤”"
logo: "/assets/images/avatar.png"
language: "vi"

## global assets will be loaded in head
css:
  - "/assets/css/variables.css"
  - "/assets/css/common.css"
js:
  - "/assets/js/jquery-3.6.0.min.js"
  - "/assets/js/main.js"

## menu
menu:
  - name: "Trang chá»§"
    url: "/"

## tags
tag_path: "/tags/"
tag_prepend: "#"
tag_related_title: "Tags"
tag_archive_title: "All tags"

## date
date_pretty_format: "%B %d, %Y"
date_today: "HÃ´m nay"
date_singular_day_ago: "1 ngÃ y trÆ°á»›c"
date_plural_days_ago: "[n] ngÃ y trÆ°á»›c"
date_singular_month_ago: "1 thÃ¡ng trÆ°á»›c"
date_plural_months_ago: "[n] thÃ¡ng trÆ°á»›c"
date_singular_year_ago: "1 nÄƒm trÆ°á»›c"
date_plural_years_ago: "[n] nÄƒm trÆ°á»›c"

## post
post_related_max: 3
post_related_title: "BÃ i viáº¿t liÃªn quan"
post_recent_title: "BÃ i viáº¿t gáº§n Ä‘Ã¢y"
post_manual_select_title: "BÃ i viáº¿t liÃªn quan do tá»± tay tui chá»n ğŸ¤ª"

## read time
min_read: "phÃºt Ä‘á»c"
words_per_min: 180